# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '427e180d-b10c-49ad-a613-06e8491acde3'

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: './pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    options: '-DskipTests=true'

- task: CopyFiles@2
  displayName: 'Copy Files to artifact staging directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/target/*.?(war|jar)'
    TargetFolder: $(Build.ArtifactStagingDirectory)

- upload: $(Build.ArtifactStagingDirectory)
  artifact: drop

- task: AzureSpringCloud@0
  inputs:
    azureSubscription: $(azureSubscription)
    Action: 'Deploy'
    AzureSpringCloud: '/subscriptions/427e180d-b10c-49ad-a613-06e8491acde3/resourceGroups/pet-clinic-grp/providers/Microsoft.AppPlatform/Spring/spring-pet-app'
    AppName: 'pet-clinic'
    DeploymentType: 'Artifacts'
    UseStagingDeployment: true
    Package: '$(System.DefaultWorkingDirectory)/**/spring-petclinic-3.1.0-SNAPSHOT.jar'
